### PR TITLE
Update theme

### PR DESCRIPTION
**Pull request by azjezz**
Make it ~dark~ beautiful  :rose: 

image

### CODE REVIEW

**Comment by azjezz** [comment]
@javiereguiluz :+1: wdyt ?

**Comment by Nyholm** [comment]
Oh. That is amazing @azjezz. Thank you. I like how you added the contribution count in the header. I was not aware that anybody found this repo. 

I just pushed some design myself. (Not much). Basically a big image and some text. 

Screenshot 2019-09-28 at 15 15 50

What do you think?

**Comment by azjezz** [comment]
@Nyholm i like it, but i don't think the image is a good fit since its from a past conference, i have update the design ( made it simpler ), you can choose between the two :)

image

**Comment by Nyholm** [comment]
I've been getting some positive feedback for the image. =)

I really appreciate your work and I have to say I think this is super hard to decide since I dont have the "feeling" of what is good or not. Writing code is so much easier...

I will close this PR and go with the current design.

**Pull request closed without merging**
